# Data Science with Python

## NumPy
- Scientific and Numerical Computing in Python
- Powerful N-Dimensional Arrays
- Easy to Use
- Perfromant (core is C/C++)
- Wide range of hardware/computing, works with GPU etc.
  
## Array

In [104]:
import numpy as np

print(np.__version__)

2.2.6


In [105]:
l1 = [1,2,3,4,5,6,7]

In [106]:
a1 = np.array(l1)
a1

array([1, 2, 3, 4, 5, 6, 7])

In [107]:
type(a1)

numpy.ndarray

In [108]:
np.shape(a1)

(7,)

In [109]:
a2 = np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [110]:
np.shape(a2)

(2, 3)

In [111]:
print(a2[1,1])
print(a2[1,2])
print(a2[1,0])
print(a2[0,1])

5
6
4
2


In [112]:
a3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
a3 = np.array([
                [[1,2],[3,4]],
                [[5,6],[7,8]],
                [[9,10],[11,12]]
                ])

a3

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [113]:
np.shape(a3)

(3, 2, 2)

In [114]:
a3b = np.array([
                [[1,2,1],
                 [3,4,2]],
                [[5,6,3],
                 [7,8,4]],
                [[9,10,5],
                 [11,12,6]]
                ])

a3b

array([[[ 1,  2,  1],
        [ 3,  4,  2]],

       [[ 5,  6,  3],
        [ 7,  8,  4]],

       [[ 9, 10,  5],
        [11, 12,  6]]])

In [115]:
np.shape(a3b)

(3, 2, 3)

In [116]:
np.where(a3b==2)

(array([0, 0]), array([0, 1]), array([1, 2]))

In [117]:
np.where(a3b==12)

(array([2]), array([1]), array([1]))

In [118]:
np.where(a3b==30)

(array([], dtype=int64), array([], dtype=int64), array([], dtype=int64))

In [119]:
z1 = np.zeros(4)
z1

array([0., 0., 0., 0.])

In [120]:
z2 = np.zeros((3,4))
z2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [121]:
ones1 = np.ones((2,3,1),dtype=int)
ones1

array([[[1],
        [1],
        [1]],

       [[1],
        [1],
        [1]]])

## Matrix

[1, 2]  row matrix

_   _
| 1 |
| 2 |     column matrix
-   -

## Scalar

Has magnitude, not direction. Single value

## Vector
Has direction and magnitude

## Matrix Multiplication
Number of rows in the first matrix, needs to be same as the number of columns in the second matrix

In [122]:
# Matrix Addition

# matrix multiplication
from random import randint

a6 = np.random.randint(10,100,)   # low num, high num, size
a6

18

In [123]:
a7 = np.random.randint(10,100,(2,2,2))
a7

array([[[32, 76],
        [93, 56]],

       [[17, 59],
        [72, 20]]])

In [124]:
arr1 = np.random.randint(1,30, size=(2,3))
arr1

array([[13, 23,  9],
       [24, 14, 14]])

In [125]:
arr2 = np.random.randint(20,40,(2,3))
arr2

array([[33, 28, 31],
       [30, 31, 38]])

In [126]:
ans = np.sum(arr1,1)
ans

array([45, 52])

In [127]:
arr = np.add(arr1,arr2)
arr

array([[46, 51, 40],
       [54, 45, 52]])

In [128]:
x = arr.copy()
arr[0] = 19
print(arr,"\n")
print(x)

[[19 19 19]
 [54 45 52]] 

[[46 51 40]
 [54 45 52]]


In [129]:
y = arr.view()   # acts like a pointer
y

array([[19, 19, 19],
       [54, 45, 52]])

In [130]:
arr[0,1]=999
y

array([[ 19, 999,  19],
       [ 54,  45,  52]])

In [131]:
y[0,0] = 0
print(arr,"\n")

[[  0 999  19]
 [ 54  45  52]] 



In [137]:
arr1 = np.array([[1,23,4,5,6],[2,3,2,4,5]])
arr1

array([[ 1, 23,  4,  5,  6],
       [ 2,  3,  2,  4,  5]])

In [ ]:
arrreshaped = arr1.reshape(5,2)
arrreshaped

array([[ 1, 23],
       [ 4,  5],
       [ 6,  2],
       [ 3,  2],
       [ 4,  5]])

In [141]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a11 = a.reshape(2,3,2)
a11

ValueError: cannot reshape array of size 10 into shape (2,3,2)

In [143]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a11 = a.reshape(2,3,2)    # 2x3x2 is 12 element array, so need additional in the array
a11

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [152]:
for element in a11:
    print(element)

[[1 2]
 [3 4]
 [5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [145]:
for element in a11:
    for element in element:
        print(element)

[1 2]
[3 4]
[5 6]
[7 8]
[ 9 10]
[11 12]


In [146]:
for element in a11:
    for element in element:
        for element in element:
            print(element)

1
2
3
4
5
6
7
8
9
10
11
12


In [153]:
for element in np.nditer(a11):
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12


In [157]:
ar1 = np.array([1,2,3,4])
ar2 = np.array([7,8,9,10])
com = np.concatenate((ar1,ar2))
com

array([ 1,  2,  3,  4,  7,  8,  9, 10])

In [158]:
ar1 = np.array([[1,2],[3,4]])
ar2 = np.array([[7,8],[9,10]])
com = np.concatenate((ar1,ar2))
com

array([[ 1,  2],
       [ 3,  4],
       [ 7,  8],
       [ 9, 10]])

In [160]:
ar1 = np.array([[1,2],[3,4]])
ar2 = np.array([[7,8],[9,10]])
com = np.concatenate((ar1,ar2),axis = 1)
com

array([[ 1,  2,  7,  8],
       [ 3,  4,  9, 10]])

In [ ]:
ar1 = np.array([[1,2],[3,4]])
ar2 = np.array([[7,8],[9,10]])
com = np.concatenate((ar1,ar2),axis = 0) # axis 0 is default, for column
com

array([[ 1,  2],
       [ 3,  4],
       [ 7,  8],
       [ 9, 10]])

In [167]:
ar1 = np.array([[1,2],[3,4]])
ar2 = np.array([[7,8],[9,10]])
com = np.concatenate((ar1,ar2),axis = 90)
com

AxisError: axis 90 is out of bounds for array of dimension 2

In [ ]:
newarr1 = np.array([1,2,3,4])
newarr2 = np.array([5,6,7,8])
comarr = np.stack((newarr1,newarr2))
comarr

# stack converts the rows into columns


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [174]:
horizontal_stack = np.hstack((newarr1,newarr2))
horizontal_stack

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
concatarr = np.concat((newarr1,newarr2),0)
concatarr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [177]:
arr = np.random.randint(1,40,12)
filter_arr = []

for element in arr:
    if element%2 ==0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
filter_arr

[False,
 True,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False]

In [188]:
arr = np.array([20,10,3,8,9,4,5,7])


In [189]:
filter_arr = []
for element in arr:
    if element%2 ==0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
filter_arr


[True, True, False, True, False, True, False, False]

In [ ]:
newarr = arr[filter_arr]
newarr

array([20, 10,  8,  4])

In [201]:
newarr = []
for element in arr:
    if element%2 ==0:
        newarr.append(element)

newarr = np.array(newarr)
newarr

array([20, 10,  8,  4])