In [ ]:
import numpy as np

matrix = np.random.randint(0,150,(4,4))

print(f"Original Matrix:\n{matrix}")

print(np.amin(matrix[0]))

littlematrix = np.array([],dtype=int)
for row in matrix:
    #### no need min_value = np.array([np.amin(row)])
    littlematrix = np.concatenate([littlematrix, [np.amin(row)]])



bigmatrix = np.max(matrix,axis=1)   # other way to achieve same thing.

print(littlematrix)

print(bigmatrix)

Original Matrix:
[[104  58  53  21]
 [ 74  76  45  33]
 [128   7  84  75]
 [ 36  91  67  39]]
21
[21 33  7 36]
[104  76 128  91]


In [7]:
print(np.amin(matrix[0]))
print(np.amin(matrix[1]))
print(np.amin(matrix[2]))

2
8
35


In [11]:
for i in range(0, 4):
    print(i)


0
1
2
3
