# Arrays

## 2-D Arrays

In [37]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0,1])

print(arr.ndim)   # shows the dimension of the array

2nd element on 1st row:  2
2


## Slicing Arrays

In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[::2])    # every other 2 numbers

[1 3 5 7]


### Slicing 2-D array

In [62]:
import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[1, 1:4]) # 2nd to 4th from second array

print(arr[0, 0:2])  # 1st to second from first array

print(arr[0:2,2]) # 3rd number from each array

print(arr[0:2,3:5]) # 4th and 5th from each array

print(type(arr))

[7 8 9]
[1 2]
[3 8]
[[ 4  5]
 [ 9 10]]
<class 'numpy.ndarray'>


## Copying an array

In [25]:
import numpy as np

arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[3] = 42

print(arr)
print(x)

[ 1  2  3 42  5]
[1 2 3 4 5]


## Print the shape of a 2-D array

In [40]:
import numpy as np

arr = np.array([1,2,3,4], ndmin=5)  # tells it to create it as a 5 dimensional one

print(arr)
print(f"Shape of array: {arr.shape}")

[[[[[1 2 3 4]]]]]
Shape of array: (1, 1, 1, 1, 4)


## Reshape Array

All elements have to be mapped.

In [2]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr = arr.reshape(3, 4)

print(newarr)

newarr = arr.reshape(2, 6)

print(" \n\n",newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
 

 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [17]:
import numpy as np

arr = np.array([[[1,2],[3,4],[5,6],[7,8]]])


for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [20]:
import numpy as np

arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

arr = np.concatenate((arr1,arr2))

print(arr)

[1 2 3 4 5 6]


In [ ]:
# Split Array

import numpy as np

arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr,3)

print(newarr)

# this is a LIST containing 3 arrays

print("\n\n",newarr[0][1])

[array([1, 2]), array([3, 4]), array([5, 6])]


 2


In [31]:
# Split into 4 arrays

import numpy as np

arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr,4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [58]:
import numpy as np

arr = np.array([1,2,3,4,5,4,4])

x = np.where(arr == 4)

print(x)
print(type(x))

(array([3, 5, 6]),)
<class 'tuple'>


In [ ]:
import numpy as np
arr = np.array([100,12,34,4,15,6])
print(np.sort(arr))
print(np.sort(arr)[::-1])  # descending order  [start:stop:step]



[  4   6  12  15  34 100]
[100  34  15  12   6   4]
